# Generated by Django 4.2 on 2023-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='number_of_pizzas',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
