# Generated by Django 4.2 on 2023-05-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('offer', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='contactInformation',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='user.contactinformation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='customerAccount',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='user.customeraccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='offer',
            field=models.ManyToManyField(blank=True, to='offer.offers'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.paymentinformation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
