# Generated by Django 4.2 on 2023-05-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
