# Generated by Django 4.2 on 2023-05-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customeraccount_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeraccount',
            name='password',
        ),
    ]
