# Generated by Django 4.2 on 2023-05-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customeraccount_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(blank=True, default='/static/images/profile_icon.png', max_length=8),
        ),
    ]
