# Generated by Django 4.2 on 2023-05-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customeraccount_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='profile_image',
            field=models.ImageField(blank=True, default='/static/images/profile_icon.png', max_length=9999, upload_to=''),
        ),
    ]
