# Generated by Django 4.2 on 2023-05-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_customeraccount_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='phone',
            new_name='house_name',
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='street_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
