# Generated by Django 4.2 on 2023-05-10 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_phone_contactinformation_house_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactinformation',
            old_name='house_name',
            new_name='house_number',
        ),
    ]
