# Generated by Django 4.2 on 2023-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_house_name_contactinformation_house_number'),
        ('user', '0011_alter_customeraccount_profile_image'),
    ]

    operations = [
    ]
