# Generated by Django 4.2 on 2023-05-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_merge_20230512_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='phone_number',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
