# Generated by Django 4.2 on 2023-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
        ('cart', '0002_remove_order_pizza_order_contactinformation_and_more'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.CharField(blank=True, max_length=9999),
        ),
        migrations.AddField(
            model_name='pizza',
            name='offer',
            field=models.ManyToManyField(blank=True, to='offer.offers'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='order',
            field=models.ManyToManyField(blank=True, to='cart.order'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='details',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='size',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='menu.toppings'),
        ),
    ]
