# Generated by Django 4.2 on 2023-05-03 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_toppings_remove_details_image_pizza_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='pizza',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='menu.pizza'),
            preserve_default=False,
        ),
    ]
