# Generated by Django 4.2 on 2023-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_details_image_details_pizza'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Details',
        ),
    ]
