# Generated by Django 4.2 on 2023-05-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('menu', '0004_pizza_description_delete_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
